language:
  - node_js

node_js:
  - 12

before_script:
  - npm run clean
  - npm run install
  - npm run compile
  - npm clean-install --only=production

script:
  - npm run start

after_script:
  - npm run clean

deploy:
  provider: heroku
  api_key: "heroku_api_key"
  run:
    - npm run clean
    - npm install
    - npm run compile
    - npm clean-install --only=production
    - npm run start
